// Code generated by MockGen. DO NOT EDIT.
// Source: base.go
//
// Generated by this command:
//
//	mockgen -source=base.go -destination=mock_base.go -typed
//

// Package epository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockDocument is a mock of Document interface.
type MockDocument struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentMockRecorder
	isgomock struct{}
}

// MockDocumentMockRecorder is the mock recorder for MockDocument.
type MockDocumentMockRecorder struct {
	mock *MockDocument
}

// NewMockDocument creates a new mock instance.
func NewMockDocument(ctrl *gomock.Controller) *MockDocument {
	mock := &MockDocument{ctrl: ctrl}
	mock.recorder = &MockDocumentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocument) EXPECT() *MockDocumentMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockDocument) GetID() bson.ObjectID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(bson.ObjectID)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockDocumentMockRecorder) GetID() *MockDocumentGetIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockDocument)(nil).GetID))
	return &MockDocumentGetIDCall{Call: call}
}

// MockDocumentGetIDCall wrap *gomock.Call
type MockDocumentGetIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentGetIDCall) Return(arg0 bson.ObjectID) *MockDocumentGetIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentGetIDCall) Do(f func() bson.ObjectID) *MockDocumentGetIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentGetIDCall) DoAndReturn(f func() bson.ObjectID) *MockDocumentGetIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetCreatedAtAndUpdatedAt mocks base method.
func (m *MockDocument) SetCreatedAtAndUpdatedAt() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCreatedAtAndUpdatedAt")
}

// SetCreatedAtAndUpdatedAt indicates an expected call of SetCreatedAtAndUpdatedAt.
func (mr *MockDocumentMockRecorder) SetCreatedAtAndUpdatedAt() *MockDocumentSetCreatedAtAndUpdatedAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCreatedAtAndUpdatedAt", reflect.TypeOf((*MockDocument)(nil).SetCreatedAtAndUpdatedAt))
	return &MockDocumentSetCreatedAtAndUpdatedAtCall{Call: call}
}

// MockDocumentSetCreatedAtAndUpdatedAtCall wrap *gomock.Call
type MockDocumentSetCreatedAtAndUpdatedAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentSetCreatedAtAndUpdatedAtCall) Return() *MockDocumentSetCreatedAtAndUpdatedAtCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentSetCreatedAtAndUpdatedAtCall) Do(f func()) *MockDocumentSetCreatedAtAndUpdatedAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentSetCreatedAtAndUpdatedAtCall) DoAndReturn(f func()) *MockDocumentSetCreatedAtAndUpdatedAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetID mocks base method.
func (m *MockDocument) SetID(_id bson.ObjectID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetID", _id)
}

// SetID indicates an expected call of SetID.
func (mr *MockDocumentMockRecorder) SetID(_id any) *MockDocumentSetIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockDocument)(nil).SetID), _id)
	return &MockDocumentSetIDCall{Call: call}
}

// MockDocumentSetIDCall wrap *gomock.Call
type MockDocumentSetIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentSetIDCall) Return() *MockDocumentSetIDCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentSetIDCall) Do(f func(bson.ObjectID)) *MockDocumentSetIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentSetIDCall) DoAndReturn(f func(bson.ObjectID)) *MockDocumentSetIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Validate mocks base method.
func (m *MockDocument) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockDocumentMockRecorder) Validate() *MockDocumentValidateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockDocument)(nil).Validate))
	return &MockDocumentValidateCall{Call: call}
}

// MockDocumentValidateCall wrap *gomock.Call
type MockDocumentValidateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentValidateCall) Return(arg0 error) *MockDocumentValidateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentValidateCall) Do(f func() error) *MockDocumentValidateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentValidateCall) DoAndReturn(f func() error) *MockDocumentValidateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidatePreSave mocks base method.
func (m *MockDocument) ValidatePreSave() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePreSave")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePreSave indicates an expected call of ValidatePreSave.
func (mr *MockDocumentMockRecorder) ValidatePreSave() *MockDocumentValidatePreSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePreSave", reflect.TypeOf((*MockDocument)(nil).ValidatePreSave))
	return &MockDocumentValidatePreSaveCall{Call: call}
}

// MockDocumentValidatePreSaveCall wrap *gomock.Call
type MockDocumentValidatePreSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocumentValidatePreSaveCall) Return(arg0 error) *MockDocumentValidatePreSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocumentValidatePreSaveCall) Do(f func() error) *MockDocumentValidatePreSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocumentValidatePreSaveCall) DoAndReturn(f func() error) *MockDocumentValidatePreSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
