version: "3.9"

services:
  back:
    image: ghcr.io/aristidewafo/time-manager/back:latest
    ports:
      - "8080:8080"
    networks:
      - internal

  front:
    image: ghcr.io/aristidewafo/time-manager/front:latest
    ports:
      - "3000:80"
    networks:
      - internal

  nginx:
    image: ghcr.io/aristidewafo/time-manager/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - back
      - front
    networks:
      - internal

networks:
  internal:
    driver: bridge
