sonar.projectKey=AristideWafo_Time-Manager
sonar.organization=aristidewafoproject


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Time-Manager
sonar.projectVersion=1.0


# Source code
sonar.sources=front/src,back
sonar.exclusions=front/node_modules/**,front/dist/**,back/vendor/**,**/*_test.go,**/*.spec.ts,**/*.test.ts

# Test coverage
sonar.tests=front/src,back
sonar.test.inclusions=**/*.spec.ts,**/*_test.go
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info
sonar.go.coverage.reportPaths=back/coverage.out

# Language settings
sonar.typescript.file.suffixes=.ts,.tsx
sonar.javascript.file.suffixes=.js,.jsx
sonar.go.file.suffixes=.go