name: Packaging

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACK: ${{ github.repository }}/backend
  IMAGE_NAME_FRONT: ${{ github.repository }}/frontend
  IMAGE_NAME_NGINX: ${{ github.repository }}/nginx

jobs:
  packaging:
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.head.ref, 'front') || contains(github.event.pull_request.head.ref, 'back'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build image
        run: |
          if [[ "${{ github.ref_name }}" == *front* ]]; then
            docker build -t $REGISTRY/${IMAGE_NAME_FRONT,,}:latest ./front
          elif [[ "${{ github.ref_name }}" == *back* ]]; then
            docker build -t $REGISTRY/${IMAGE_NAME_BACK,,}:latest ./back
            docker build -t $REGISTRY/${IMAGE_NAME_NGINX,,}:latest ./nginx
          else
            echo "no match"
          fi
                
      - name: Push image
        run: |
          if [[ "${{ github.ref_name }}" == *front* ]]; then
            docker push $REGISTRY/${IMAGE_NAME_FRONT,,}:latest
          elif [[ "${{ github.ref_name }}" == *back* ]]; then
            docker push $REGISTRY/${IMAGE_NAME_BACK,,}:latest
            docker push $REGISTRY/${IMAGE_NAME_NGINX,,}:latest
          else
            echo "no match"
          fi
