name: Test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test app
        run: echo "Testing for ${{ inputs.environment }}"
  
  go-lint: 
      if: contains(github.event.pull_request.head.ref, '/back_')   
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-go@v6
          with:
            go-version: stable
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            version: v2.1
