name: Test

env:
  GO_VERSION: '1.25.1'
  WORKING_DIR: './back'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

  pull_request:
    branches: [ "dev","feat/*","fix/*"  ]
  push:
    branches: [ "prod","feat/*","fix/*" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test app
        run: echo "Testing for ${{ inputs.environment }}"
  
  go-lint:
    if: contains(github.ref_name, 'cicd') || contains(github.ref_name, 'back_')
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}  # Exact version from go.mod
      
      - name: Ensure deps
        working-directory: ${{ env.WORKING_DIR }}
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        working-directory: ./back
        run: golangci-lint run --timeout=5m